apiVersion: action.lkc-lab.com/v1
kind: Action
metadata:
  labels:
    app.kubernetes.io/name: action
    app.kubernetes.io/instance: action-sample
    app.kubernetes.io/part-of: agh3-action
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: agh3-action
  name: action-sample
spec:
  # TODO(user): Add fields here
